name = input('Enter your name? ')
address = input('Enter your address with city, state, and zip? ')
number = input('Enter your number? ')
college_major = input('Enter your major? ')
print('name:', name)
print('address:', address)
print('number:', number)
print('college_major:', college_major)
